### PR TITLE
Sohambapat kingdelegation

### LINKED ISSUE #27: Bishop core death and reassignment
Whenever a bishop is captured, its corp should be moved to the king's corp. The maximum amount of actions for the captured bishop's color should also decrease by 1.

Some methods are already in place that should help with this issue, like 'reassignAll' in the Piece class, though it is currently untested so use caution.

### LINKED ISSUE #30: King delegation
The King may delegate any of its pieces to be commanded by either Bishop, at any time.

Basically, this means a unit in the King's corp can use one of the bishop corps actions to move; a piece in the king corp can move/attack using up a bishop corps action instead of the king's. This means any single Piece in the king's corp can act up to 3 times in one turn by allowing the bishops to command said Piece.

This issue is related to #31 , so be sure to work together. (How to choose which corp to delegate to)

### PR DESCRIPTION
**Pull request by sohambapat**
king delegation problem solved

### CODE REVIEW

**Comment by sohambapat** [comment]
Now any of the king corp pieces can move up to 3 times and the turn color flips after 3 turns just as before

**Comment by Quarz8** [comment]
@sohambapat Since this PR shares the same commit history, I am going to close #37

**Review by Quarz8 — CHANGES_REQUESTED** [review]
The king delegation only works for movement. If a member of a king's corp attacks, the corp as a whole can no longer act. plz fix

**Comment by sohambapat** [comment]
Please review the latest code in kingDelegation branch. The attacking issue should be fixed.

**Review by Quarz8 — APPROVED** [review]
Everything seems to work now; very good.

**Pull request merged**
