### PR TITLE
Updated Tabular How To Play and Skip Button

### LINKED ISSUE #4: In game rules out of date
The "how to play button" displays outdated rules when clicked. Should be an extremely easy fix.

### LINKED ISSUE #24: Die Roll Display in GUI
Display the die roll from attacking in the GUI, and if it is successful.

### LINKED ISSUE #32: End/skip turn button
We need a button to skip the current player's turn, as one can end their turn at any time.

Remember to reset the actions taken that turn and reset corps hasActed variable.

### PR DESCRIPTION
**Pull request by scrowley0**
Closing #4. Working on skip button functionality.

### CODE REVIEW

**Comment by scrowley0** [comment]
Skip button functionality added. Required making the gBoard variable in GamePanel a static variable. There shouldn't be any problem, but do let me know if this breaks your code.

**Review by Quarz8 — DISMISSED** [review]
lgtm :+1:

**Comment by scrowley0** [comment]
SUMMARY: Updated How to Play tabs, new functional skip button, and die roll display. The die display images are temporary.

**Review by Quarz8 — CHANGES_REQUESTED** [review]
Since the die images don't exist, the code cannot run. Can't really test or approve this until we have some sort of image for the die.
Could use literally any image as long as it is in the folder and is different for each die face.

**Comment by scrowley0** [comment]
my bad, I thought they were added, should be good now

**Review by Quarz8 — APPROVED** [review]

**Review by Quarz8 — APPROVED** [review]
thanks

**Review by sohambapat — APPROVED** [review]
The skip button works well.

**Pull request merged**
